remote_theme: pages-themes/cayman@v0.2.0

plugins:
- jekyll-remote-theme 

title: [Charlie Caravati]
description: [Currently studying Earth Data Analytics at CU Boulder. Some of the projects I have worked on are listed below and linked for further detail.]
